### ISSUE TITLE
Zoom function is not working

### ISSUE THREAD

**Issue by susylPearl** [ldn0x7dc/react-native-transformable-image#1]
when i zoom an image it doesnot get static, it goes to its original position, and also double tap features is not available in android.

**Comment by ldn0x7dc** [comment]
@susylPearl 
I guess you must have noticed the **pixels** prop now~

**Comment by susylPearl** [comment]
i want to disable dragging image feature, can i do ? when i zoom image after inserting it in viewpager image disappear for certain seconds and it gets zoomed , what are problems facing behind this?
