### ISSUE TITLE
Image bounces back once touch is released

### ISSUE THREAD

**Issue by DroneKid** [ldn0x7dc/react-native-transformable-image#13]
Hi,

once I release touch, the image bounces back to original position and size. Any idea what the problem might be?

**Comment by VlCTORlOUS** [comment]
Any update on this one?

**Comment by muszu** [comment]
There is no problem :)

https://github.com/ldn0x7dc/react-native-view-transformer

> onTransformGestureReleased : a callback called when the transform gesture is released, receiving current transform object, {scale: xxx, translateX: xxx, translateY: xxx}. Return true to abort further animations like bounce back.


So just add:
`onTransformGestureReleased={() => true}`
to prevent image to bounce back

**Comment by DroneKid** [comment]
It's worth mentioning it in `react-native-transformable-image` docs maybe.

**Comment by Lump01** [comment]
### I solved double tap zooming and pinch zooming not staying by implementing the following minor code changes in TransformableImage/index.js:


```
let maxScale = 5;                            // change to whatever you want the max zoom in state to be
let contentAspectRatio;
let width, height; // imageDimensions

if (imageDimensions) {
    width = imageDimensions.width;
    height = imageDimensions.height;
}

if (width && height) {
    contentAspectRatio = width / height;
    // if (viewWidth && viewHeight) {         // code preventing zoom from staying based on image resolution
    //     maxScale = Math.max(width / viewWidth, height / viewHeight); 
    //     maxScale = Math.max(1, maxScale);
    // }
}
```
