### ISSUE TITLE
Image zoom problems.

### ISSUE THREAD

**Issue by susylPearl** [ldn0x7dc/react-native-transformable-image#2]
When i zoom image it move towards left side of screen and disappear for seconds, and gets zoomed after than. Again when i pinched image it moves towards right side of screen and same things happens as it gets lost for some seconds. What might be the problems? i inserted this image component inside viewpagerAndroid.

**Comment by ldn0x7dc** [comment]
@susylPearl 
Pls check:
1. Did you provide a correct pixels prop to the component? For example, if the image's pixels are 1920x1080, use `pixels={{width: 1920, height: 1080}}`.(This is **optional** if you are using react-native v0.28+ and **the image is remote**). The component must know the correct aspect of your image.
2. Pls try wrapping this component in a normal view(not a scrollable view like viewpager) and check if it works ok.

**Comment by susylPearl** [comment]
yes, it works fine when i wrap it to normal view. But if i want to show it inside viewpager than what should i do? I also want to disable its dragging feature. Can i do it?

**Comment by ldn0x7dc** [comment]
@susylPearl 
1. The viewpager issue: I'll look into it later. And I'm also planning to implement a component like image gallery.
2. The disable option is not provided for now, pls wait for future releases.
This component is still in early development. I'll let you know when it works better~

**Comment by susylPearl** [comment]
oh man i am really in trouble now than....... i have to made this feature as soon as possible. Than should i now implement another library for viewing images??

**Comment by ldn0x7dc** [comment]
@susylPearl 
I understand your feelings~I'll get to work on it in a few hours.

**Comment by susylPearl** [comment]
ok sure.....

**Comment by ldn0x7dc** [comment]
@susylPearl 
A new release(0.0.5) is available.
The viewpager issue should have been fixed now.
And you can pass `enableTransform={{false}}` to disable all transform gestures.

**Comment by susylPearl** [comment]
i have implemented the new version, everything comes what i expected but when i swipe the images inside viewpager, sometimes error occurs as: transformedRect...invalid rect

**Comment by ldn0x7dc** [comment]
@susylPearl 
I have noticed this bug and fixed it just now(not released yet, but soon).
I'm working on a more elegant gallery component and pls just wait a few more hours.

**Comment by susylPearl** [comment]
ok dude.

**Comment by susylPearl** [comment]
image also not rendering please look at this also.

**Comment by ldn0x7dc** [comment]
@susylPearl 
1. pls check out the latest release to see if your problems are solved;
2. I've worked out a new component **[react-native-gallery](https://github.com/ldn0x7dc/react-native-gallery)**. Instead of using ViewPagerAndroid, I use a ListView to be the wrapper. If it meets your needs, welcome to install and test it.

**Comment by susylPearl** [comment]
i want to disable transform but i dont want to disable zooming features and tap features can i achieved this in react-native-transformable-image?

**Comment by ldn0x7dc** [comment]
@susylPearl 
The latest release provides `enableTransform` , `enableScale` and `enableTranslate` props to control corresponding features.
If you want to enable scale but disable scroll, use `enableScale = {true}` and `enableTranslate={false}`, but this is quite s strange feature.

**Comment by ajaykumar97** [comment]
Does not work smoothly inside viewPagerAndroid. I am using react-native-transformable-image inside react-native-swiper. Zooming and scaling is working perfectly, but scrolling does not work accurately. Sometimes scroll works or sometimes it does not. Also, I am having react-native-swiper inside a modal and Platform in android. Please help me if anyone has the solution.
