### ISSUE TITLE
Cropping using this module?

### ISSUE THREAD

**Issue by ghost** [ldn0x7dc/react-native-transformable-image#35]
HI guys. By any chance, any of you know how to use this module to perform a crop on the transformed image? From what I've tried, it feels like this module isn't really appropriate for cropping attempts as it really just transform the image scale/translation.
Hints welcome.

**Comment by Werewolve** [comment]
@kytwb any updates on this?

**Comment by ghost** [comment]
@Werewolve I went on to use [`react-native-image-cropper`](https://github.com/stoffern/react-native-image-cropper)

**Comment by Werewolve** [comment]
@kytwb Thanks for the tip, but I'm using Expo and don't want to detach.
